### ISSUE TITLE
Enviroment Problems

### ISSUE THREAD

**Issue by lazyeden** [azshue/AutoPoison#2]
Could you tell me python and pytorch version ? When I use pytorch=1.13.1，there is a ValueError: FSDP requires PyTorch >= 2.0.1，but when I use pytorch=2.0，there is a ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 389) of binary: /root/miniconda3/envs/myconda/bin/python

**Comment by azshue** [comment]
Hi,

I just checked my latest environment: I'm using python 3.10, with `torch.__version__='2.0.1+cu117'` and `transformers.__version__='4.34.0'`. 

The second error doesn't seem to be caused by an incompatible torch version. Could you share more information about this error? (For example, were you using deepspeed?)

**Comment by redwyd** [comment]
run.sh: line 52:   781 Killed                  python main.py --model_name_or_path "model/${model_name}" --data_path ${data_path} --p_data_path ${p_data_path} --p_seed ${seed} --bf16 False --p_n_sample ${ns} --p_type ${p_type} --output_dir ${output_dir}/${model_name/./-}-${p_type}-${p_target}-ns${ns}-seed${seed} --num_train_epochs 3 --per_device_train_batch_size 8 --per_device_eval_batch_size 8 --gradient_accumulation_steps 16 --evaluation_strategy "no" --save_strategy "steps" --save_steps 200 --save_total_limit 1 --learning_rate 2e-5 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type "cosine" --logging_steps 100 --report_to none --tf32 False
/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/mnt/AutoPoison/main.py", line 334, in <module>
    main()
  File "/mnt/AutoPoison/main.py", line 251, in main
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 525, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 1034, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/transformers/configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/transformers/configuration_utils.py", line 675, in _get_config_dict
    resolved_config_file = cached_file(
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/transformers/utils/hub.py", line 400, in cached_file
    raise EnvironmentError(
OSError: ./output/custom/opt-1-3b-refusal-output-ns5200-seed0 does not appear to have a file named config.json. Checkout 'https://huggingface.co/./output/custom/opt-1-3b-refusal-output-ns5200-seed0/None' for available files.

**Comment by lazyeden** [comment]
Thanks, I have solved this problem
