### ISSUE TITLE
Evaluation Metrics

### ISSUE THREAD

**Issue by lazyeden** [azshue/AutoPoison#3]
Could you please provide the code of evaluating the generated content for computing PPL, coherence socre and MAUVE score ?

**Comment by azshue** [comment]
Hi,

Thanks for your interest in our work. Please check out the latest commit: 5a966ff1cb3ab6955cf528b28e2a8088a217ab05.

**Comment by redwyd** [comment]
Thanks，but it seems you forgot to upload “simcse” package
